name: NextJS CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm ci

      - name: Run Type Check (tsc)
        run: npm run tsc

      - name: Run Tests (jest)
        run: npm test

      - name: Run ESLint
        run: npm run lint