name: CalGen CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  app-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install Dependencies
        run: npm ci

      - name: Run Type Check (tsc)
        run: npm run tsc

      - name: Run ESLint
        run: npm run lint

  app-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests (jest)
        run: npm test

  scraper-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Install Python Dependencies
        working-directory: ./scripts
        run: pip install -r requirements.txt

      - name: Run Flake8
        working-directory: ./scripts
        run: flake8

      - name: Run mypy
        working-directory: ./scripts
        run: mypy .

  scraper-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Install Python Dependencies
        working-directory: ./scripts
        run: pip install -r requirements.txt

      - name: Run Pytest
        working-directory: ./scripts
        run: pytest
